name: "Add Release"
description: "Github Action for creating Github Releases"
author: "maluns"
inputs:
  name:
    description: "Gives the release a custom name. Defaults to tag name"
    required: false
  tag_name:
    description: "Gives a tag name. Defaults to github.GITHUB_REF"
    required: false
  body:
    description: "Note-worthy description of changes in release"
    required: false
  body_path:
    description: "Path to load note-worthy description of changes in release from"
    required: false
  draft:
    description: "Creates a draft release. Defaults to false"
    required: false
  prerelease:
    description: "Identify the release as a prerelease. Defaults to false"
    required: false
  files:
    description: "Newline-delimited list of path globs for asset files to upload"
    required: false
  repository:
    description: "Repository to make releases against, in <owner>/<repo> format"
    required: false
  token:
    description: "Authorized secret GitHub Personal Access Token. Defaults to github.token"
    required: false
    default: ${{ github.token }}
  target_commitish:
    description: "Commitish value that determines where the Git tag is created from. Can be any branch or commit SHA."
    required: false
  generate_release_notes:
    description: "Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes."
    required: false
  input_generate_by_commit:
    description: "Whether to automatically generate this version of the body according to the commit record."
    required: false
  input_generate_by_commit_rules:
    description: "Submit record resolution rules."
    required: false
env:
  "GITHUB_TOKEN": "As provided by Github Actions"
outputs:
  url:
    description: "URL to the Release HTML Page"
  id:
    description: "Release ID"
  upload_url:
    description: "URL for uploading assets to the release"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "package"